<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    const promise = (text, time) => { // 매개변수는 아래에서 작성한 text 1 과 1000이 각각 받아짐 
        return new Promise((res, rej)=>{
            // try 문 안의 내용에서 오류가 발생하면 catch 문으로 넘어간다.
            try {
            setTimeout(() => {
                res(text)
            }, time);
            } catch (error) {
                // try문 안의 코드의 에러가 발생하면 rej를 호출
            rej(error)
            }
    })
    }
//--------------- then 사용
    promise("text 1", 1000).then(result => {
        console.log(result)
        return promise("text 2", 3000);
    }).then ((result => {
        console.log(result)
        return promise("text 3", 3000)
    })).then ((result =>{
        console.log(result)
    }))
//--------------- 바로 위 코드 간추리기 await 사용
    const asyncFoo = async () => {
        // 비동기 함수 안에서 코드의 내용이 동기적으로 실행되어야 한다.
        const data = await promise ("text 1", 1000);// 게시글 데이터를 가져올것 나중에
        // 비동기로 실행되는 코드를 대기하고 완료되면 밑의 코드 실행
        //await로 대기를 시켜서 내부에서는 동기적으로 호출할 수 있게
        console.log(data)
    }
    // promise 다음에 .then()작성해도 큰 문제는 없는데 너무 없어보이고 이해를 못했구나
    // async await만 사용하거나, then catch만 사용하거나 둘중 하나. 둘다 쓰면 안된다. 
    asyncFoo();
</script>
</html>